### ISSUE TITLE
when i shutdown my server on aternos there is an error in log file that says "The plugin 'EasyWarp' could not be disabled."

### ISSUE THREAD

**Issue by K-Andrej** [Nerdsie/EasyWarp#15]
<html>
<body>

[15:58:18] [Server thread/ERROR]: Error occurred while disabling EasyWarp v3.13 (Is it up to date?)
--
404 | java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
405 | at com.collinsrichard.easywarp.managers.FileManager.saveWarps(FileManager.java:62) ~[?:?]
406 | at com.collinsrichard.easywarp.EasyWarp.onDisable(EasyWarp.java:38) ~[?:?]
407 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
408 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-794]
409 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
410 | at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-794]
411 | at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-794]
412 | at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-794]
413 | at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:906) ~[patched_1.16.5.jar:git-Paper-794]
414 | at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-794]
415 | at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1182) ~[patched_1.16.5.jar:git-Paper-794]
416 | at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
417 | at java.lang.Thread.run(Thread.java:831) [?:?]

</body>
</html>[15:58:18] [Server thread/ERROR]: Error occurred while disabling EasyWarp v3.13 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
	at com.collinsrichard.easywarp.managers.FileManager.saveWarps(FileManager.java:62) ~[?:?]
	at com.collinsrichard.easywarp.EasyWarp.onDisable(EasyWarp.java:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:[405](https://aternos.org/log/#L405)) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:906) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:763) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1182) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by K-Andrej** [comment]
Fixed it. The problem was that i had deleted world but didnt delete warp connection to it
